-- Procurement PI snapshot tables. MySQL 5.7 compatible; relationships are enforced by the application.
CREATE TABLE IF NOT EXISTS proforma_invoices (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  pi_number VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_id INT UNSIGNED NOT NULL,
  request_version_id INT UNSIGNED NOT NULL,
  purchase_plan_id INT UNSIGNED NOT NULL,
  supersedes_pi_id INT UNSIGNED DEFAULT NULL,
  status TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '1=draft,2=approved,3=issued,4=cancelled',
  customer_user_id INT(10) DEFAULT NULL,
  company_name VARCHAR(255) DEFAULT NULL,
  contact_name VARCHAR(100) NOT NULL,
  email VARCHAR(254) NOT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  whatsapp VARCHAR(50) DEFAULT NULL,
  country VARCHAR(100) DEFAULT NULL,
  billing_address TEXT,
  delivery_address TEXT,
  seller_name VARCHAR(255) NOT NULL,
  seller_address TEXT,
  seller_email VARCHAR(254) DEFAULT NULL,
  seller_phone VARCHAR(50) DEFAULT NULL,
  currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'USD',
  product_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  packaging_fee DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  shipping_fee DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  other_fee DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  discount_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  subtotal DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  total_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  payment_terms TEXT,
  payment_instructions TEXT,
  trade_terms TEXT,
  delivery_terms TEXT,
  lead_time VARCHAR(255) DEFAULT NULL,
  valid_until INT UNSIGNED DEFAULT NULL,
  customer_note TEXT,
  internal_note TEXT,
  created_by INT UNSIGNED NOT NULL,
  updated_by INT UNSIGNED NOT NULL,
  approved_by INT UNSIGNED DEFAULT NULL,
  issued_by INT UNSIGNED DEFAULT NULL,
  cancelled_by INT UNSIGNED DEFAULT NULL,
  created_at INT UNSIGNED NOT NULL,
  updated_at INT UNSIGNED NOT NULL,
  approved_at INT UNSIGNED DEFAULT NULL,
  issued_at INT UNSIGNED DEFAULT NULL,
  cancelled_at INT UNSIGNED DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pi_number (pi_number),
  KEY idx_purchase_plan (purchase_plan_id,status,id),
  KEY idx_customer_status (customer_user_id,status,issued_at,id),
  KEY idx_request_status (request_id,status,issued_at,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS proforma_invoice_items (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  pi_id INT UNSIGNED NOT NULL,
  purchase_plan_item_id INT UNSIGNED DEFAULT NULL,
  request_item_id INT UNSIGNED DEFAULT NULL,
  product_key CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  sort_order INT UNSIGNED NOT NULL DEFAULT 0,
  product_name VARCHAR(255) NOT NULL,
  sku VARCHAR(100) DEFAULT NULL,
  brand VARCHAR(100) DEFAULT NULL,
  description TEXT,
  quantity DECIMAL(15,3) NOT NULL,
  quantity_unit VARCHAR(30) NOT NULL,
  specifications TEXT,
  color VARCHAR(255) DEFAULT NULL,
  size VARCHAR(255) DEFAULT NULL,
  packaging_requirements TEXT,
  customization_requirements TEXT,
  customer_note TEXT,
  unit_price DECIMAL(15,4) NOT NULL,
  line_amount DECIMAL(15,2) NOT NULL,
  created_by INT UNSIGNED NOT NULL,
  updated_by INT UNSIGNED NOT NULL,
  created_at INT UNSIGNED NOT NULL,
  updated_at INT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pi_product (pi_id,product_key),
  KEY idx_pi_sort (pi_id,sort_order,id),
  KEY idx_purchase_plan_item (purchase_plan_item_id),
  KEY idx_request_item (request_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;
