-- Procurement phase one: immutable quote/cost history and staged approval.
ALTER TABLE procurement_inquiries ADD COLUMN revision_no INT UNSIGNED NOT NULL DEFAULT 1 AFTER id,ADD COLUMN previous_inquiry_id INT UNSIGNED DEFAULT NULL AFTER revision_no,ADD COLUMN is_current TINYINT(1) NOT NULL DEFAULT 1 AFTER previous_inquiry_id,ADD KEY idx_procurement_inquiry_current(plan_item_id,is_current,status),ADD KEY idx_procurement_inquiry_previous(previous_inquiry_id);
CREATE TABLE IF NOT EXISTS procurement_selected_inquiries (plan_item_id INT UNSIGNED NOT NULL,inquiry_id INT UNSIGNED NOT NULL,selected_by BIGINT UNSIGNED NOT NULL,selected_at INT UNSIGNED NOT NULL,PRIMARY KEY(plan_item_id),UNIQUE KEY uk_procurement_selected_inquiry(inquiry_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
ALTER TABLE procurement_plan_cost_items ADD COLUMN plan_item_id INT UNSIGNED DEFAULT NULL AFTER plan_id,ADD COLUMN inquiry_id INT UNSIGNED DEFAULT NULL AFTER plan_item_id,ADD COLUMN cost_scope VARCHAR(20) NOT NULL DEFAULT 'shared' AFTER inquiry_id,ADD KEY idx_procurement_cost_plan_item(plan_item_id,sort_order,id),ADD KEY idx_procurement_cost_inquiry(inquiry_id);
CREATE TABLE IF NOT EXISTS procurement_cost_snapshots (
 id INT UNSIGNED NOT NULL AUTO_INCREMENT,plan_id INT UNSIGNED NOT NULL,revision_no INT UNSIGNED NOT NULL,cny_per_usd DECIMAL(15,6) NOT NULL,profit_rate DECIMAL(8,4) NOT NULL,product_cost_cny DECIMAL(15,2) NOT NULL,shared_cost_cny DECIMAL(15,2) NOT NULL,total_cost_cny DECIMAL(15,2) NOT NULL,total_cost_usd DECIMAL(15,2) NOT NULL,suggested_quote_usd DECIMAL(15,2) NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'submitted',submitted_by BIGINT UNSIGNED NOT NULL,submitted_at INT UNSIGNED NOT NULL,PRIMARY KEY(id),UNIQUE KEY uk_procurement_cost_snapshot_revision(plan_id,revision_no),KEY idx_procurement_cost_snapshot_status(plan_id,status,submitted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS procurement_cost_snapshot_items (
 id INT UNSIGNED NOT NULL AUTO_INCREMENT,snapshot_id INT UNSIGNED NOT NULL,plan_item_id INT UNSIGNED DEFAULT NULL,inquiry_id INT UNSIGNED DEFAULT NULL,cost_type_id INT UNSIGNED DEFAULT NULL,cost_name VARCHAR(120) NOT NULL,source_currency VARCHAR(3) NOT NULL DEFAULT 'CNY',quantity DECIMAL(15,3) NOT NULL DEFAULT 1,unit_amount DECIMAL(15,4) NOT NULL DEFAULT 0,amount_cny DECIMAL(15,2) NOT NULL,sort_order INT UNSIGNED NOT NULL DEFAULT 0,PRIMARY KEY(id),KEY idx_procurement_snapshot_items(snapshot_id,sort_order,id),KEY idx_procurement_snapshot_plan_item(plan_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS procurement_quote_reviews (
 id INT UNSIGNED NOT NULL AUTO_INCREMENT,plan_id INT UNSIGNED NOT NULL,cost_snapshot_id INT UNSIGNED NOT NULL,stage VARCHAR(24) NOT NULL,decision VARCHAR(24) NOT NULL,proposed_quote_usd DECIMAL(15,2) DEFAULT NULL,actual_profit_rate DECIMAL(8,4) DEFAULT NULL,note VARCHAR(1000) DEFAULT NULL,acted_by BIGINT UNSIGNED NOT NULL,acted_at INT UNSIGNED NOT NULL,PRIMARY KEY(id),KEY idx_procurement_quote_review(plan_id,stage,acted_at),KEY idx_procurement_quote_review_snapshot(cost_snapshot_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
CREATE TABLE IF NOT EXISTS procurement_workflow_events (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,plan_id INT UNSIGNED NOT NULL,event_code VARCHAR(60) NOT NULL,from_status TINYINT UNSIGNED DEFAULT NULL,to_status TINYINT UNSIGNED DEFAULT NULL,entity_type VARCHAR(40) DEFAULT NULL,entity_id BIGINT UNSIGNED DEFAULT NULL,note VARCHAR(1000) DEFAULT NULL,actor_id BIGINT UNSIGNED NOT NULL,created_at INT UNSIGNED NOT NULL,PRIMARY KEY(id),KEY idx_procurement_workflow_plan(plan_id,created_at,id),KEY idx_procurement_workflow_event(event_code,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
ALTER TABLE purchase_plan_files ADD COLUMN supplier_id INT UNSIGNED DEFAULT NULL AFTER plan_item_id,ADD COLUMN inquiry_id INT UNSIGNED DEFAULT NULL AFTER supplier_id,ADD COLUMN visibility_code VARCHAR(20) NOT NULL DEFAULT 'internal' AFTER file_type_id,ADD COLUMN checksum_sha256 CHAR(64) DEFAULT NULL AFTER storage_path,ADD KEY idx_purchase_plan_files_supplier(supplier_id,status),ADD KEY idx_purchase_plan_files_inquiry(inquiry_id,status),ADD KEY idx_purchase_plan_files_visibility(plan_id,visibility_code,status);
INSERT INTO procurement_file_types(type_code,type_name,description,allowed_extensions,max_file_size_mb,is_active,sort_order,created_at,updated_at) VALUES
('customer_source','客户原始资料','采购申请中的客户文件和补充资料',NULL,50,1,5,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),('product_spec','产品规格','内部整理的产品规格、图纸和技术要求',NULL,50,1,10,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),('promotion','推广资料','供应商产品目录、推广材料和介绍文件',NULL,50,1,20,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),('supplier_quote','供应商报价','供应商报价单及报价附件',NULL,50,1,30,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),('supplier_qualification','供应商资质','营业执照、认证和资质文件',NULL,50,1,40,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),('internal_comparison','内部比价','内部比价、核价和决策资料',NULL,50,1,60,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),('logistics','物流资料','运输、清关和交付资料',NULL,50,1,70,UNIX_TIMESTAMP(),UNIX_TIMESTAMP()),('customer_output','客户文件','PI、最终报价和其他对客文件',NULL,50,1,80,UNIX_TIMESTAMP(),UNIX_TIMESTAMP())
ON DUPLICATE KEY UPDATE type_name=VALUES(type_name),description=VALUES(description),allowed_extensions=VALUES(allowed_extensions),max_file_size_mb=VALUES(max_file_size_mb),is_active=VALUES(is_active),sort_order=VALUES(sort_order),updated_at=VALUES(updated_at);
INSERT INTO eggrack_auth_permission(permission_code,permission_name,resource_type) VALUES
('wholesale.procurement.execute','执行采购寻源','ACTION'),('wholesale.purchase-cost.edit','编辑采购成本','ACTION'),('wholesale.purchase-quote.submit','提交建议报价','ACTION'),('wholesale.purchase-quote.review','审核采购报价','ACTION'),('wholesale.purchase-quote.final-approve','最终批准采购报价','ACTION'),('wholesale.purchase-pi.manage','编制客户 PI','ACTION'),('wholesale.purchase-pi.issue','签发客户 PI','ACTION'),('wholesale.purchase-mail.send','发送采购报价邮件','ACTION'),('wholesale.purchase-document.internal','查看内部采购资料','API')
ON DUPLICATE KEY UPDATE permission_name=VALUES(permission_name),resource_type=VALUES(resource_type),status=1;
INSERT INTO eggrack_auth_role_permission(role_id,permission_id,effect)
SELECT r.id,p.id,'ALLOW' FROM eggrack_auth_role r JOIN eggrack_auth_permission p
WHERE (r.role_code='department_staff' AND p.permission_code IN ('wholesale.procurement.execute','wholesale.purchase-cost.edit','wholesale.purchase-quote.submit','wholesale.purchase-document.internal'))
 OR (r.role_code IN ('department_manager','department_admin') AND p.permission_code IN ('wholesale.procurement.execute','wholesale.purchase-cost.edit','wholesale.purchase-quote.submit','wholesale.purchase-quote.review','wholesale.purchase-pi.manage','wholesale.purchase-document.internal'))
 OR (r.role_code IN ('boss','super_admin') AND p.permission_code IN ('wholesale.procurement.execute','wholesale.purchase-cost.edit','wholesale.purchase-quote.submit','wholesale.purchase-quote.review','wholesale.purchase-quote.final-approve','wholesale.purchase-pi.manage','wholesale.purchase-pi.issue','wholesale.purchase-mail.send','wholesale.purchase-document.internal'))
ON DUPLICATE KEY UPDATE effect=VALUES(effect);
INSERT INTO eggrack_auth_role_scope(role_id,permission_id,data_scope)
SELECT r.id,p.id,CASE WHEN r.role_code IN ('boss','super_admin') THEN 'ALL' WHEN r.role_code='department_staff' THEN 'SELF_OR_DEPARTMENT' ELSE 'DEPARTMENT' END FROM eggrack_auth_role r JOIN eggrack_auth_permission p
WHERE p.permission_code IN ('wholesale.procurement.execute','wholesale.purchase-cost.edit','wholesale.purchase-quote.submit','wholesale.purchase-quote.review','wholesale.purchase-quote.final-approve','wholesale.purchase-pi.manage','wholesale.purchase-pi.issue','wholesale.purchase-mail.send','wholesale.purchase-document.internal') AND r.role_code IN ('department_staff','department_manager','department_admin','boss','super_admin')
ON DUPLICATE KEY UPDATE data_scope=VALUES(data_scope);
